import {EarthRenderer} from './renderer.js';import {Network,DataCache,GeographyProvider,ElevationProvider,LatestTask,SOURCES,checkAbort} from './providers.js';import {createTerrain} from './terrain.js';import {A,DEG,clamp,wrapLon,frameAt,toLocal,toECEF,localToGeo,norm,add,scale,directionToECEF,intersectEarth,fromECEF,location as geoLocation,moveGeodetic} from './geodesy.js';
const $=id=>document.getElementById(id),canvas=$('earth'),params=new URLSearchParams(location.search),log=(text,error=false)=>{const e=document.createElement('div');e.textContent=text;if(error)e.className='error';$('log').prepend(e);while($('log').children.length>8)$('log').lastChild.remove();},status=(text,error=false)=>{$('status').textContent=text;log(text,error);};
const camera={lat:-37.8136,lon:144.9631,height:14000000,yaw:0,pitch:-90,grid:false,provenance:false};
if(params.has('lat')&&params.has('lon')){try{Object.assign(camera,geoLocation(Number(params.get('lat')),Number(params.get('lon')),Number(params.get('alt')||1200)));}catch(e){status(e.message,true);}}
const jobs=new Map();function progress(e){let row=jobs.get(e.entry);if(!row){row=document.createElement('div');const a=document.createElement('span'),b=document.createElement('span');a.textContent=e.entry;row.append(a,b);$('boot-jobs').append(row);jobs.set(e.entry,row);}row.lastChild.textContent=e.phase==='ready'?'✓ '+(e.bytes/1024).toFixed(1)+' KB':e.phase==='pipeline'?'GPU pipeline…':'Loading CUDA…';row.classList.toggle('done',e.phase==='ready');$('boot-progress').value=e.done;}
let fatalError=false,ready=false,drawing=false,width=Number($('resolution').value),last=0,frames=0,fpsAt=performance.now(),lastInput=performance.now(),lastAutomatic=0,dataBusy=false,needsRender=true;
function fatal(e){fatalError=true;ready=false;$('boot').hidden=false;$('boot-error').textContent=String(e?.message||e);$('retry').hidden=false;status(String(e?.message||e),true);}
const renderer=new EarthRenderer(canvas,{onProgress:progress,onError:fatal}),cache=new DataCache(),network=new Network({cache,onStatus:t=>status(t)}),elevation=new ElevationProvider(network);let geography=new GeographyProvider(network);const task=new LatestTask();let selectedRecord=null;let loadEpoch=0;
const dimensions=()=>[width,Math.round(width*innerHeight/innerWidth)];
function saveURL(){const u=new URL(location.href);u.searchParams.set('lat',camera.lat.toFixed(6));u.searchParams.set('lon',camera.lon.toFixed(6));u.searchParams.set('alt',Math.round(camera.height));history.replaceState(null,'',u);}
function changed(){lastInput=performance.now();needsRender=true;}
function destination(lat,lon){const next=geoLocation(lat,lon);task.cancel();Object.assign(camera,next,{height:1000,yaw:0,pitch:-90});$('lat').value=camera.lat.toFixed(6);$('lon').value=camera.lon.toFixed(6);changed();saveURL();loadArea(true);}
async function loadArea(vectors=false,automatic=false){
 if(!ready||fatalError)return;const epoch=++loadEpoch;const lat=camera.lat,lon=camera.lon,desired=clamp(camera.height*2,1800,12000),radius=2**Math.ceil(Math.log2(desired));dataBusy=true;status('Preparing source descriptors…');
 try{const committed=await task.run(async signal=>{
   const requestID=task.generation;
   const [t,g]=await Promise.allSettled([elevation.prepare(lat,lon,radius,signal),vectors?geography.area(lat,lon,{signal,radius:600,automatic}):Promise.resolve(null)]);checkAbort(signal);
   let terrain;if(t.status==='fulfilled')terrain=createTerrain(lat,lon,radius,t.value.sample,{zoom:t.value.z});else{if(signal.aborted)throw signal.reason;terrain=createTerrain(lat,lon,radius,()=>0,{valid:false});log('Elevation unavailable: '+t.reason.message+' Using the ellipsoid datum, not invented terrain.',true);}
   let osm=null;if(g.status==='fulfilled'&&g.value)osm=g.value.json;else if(g.status==='rejected')log('Vectors unavailable: '+g.reason.message+'. No buildings invented.',true);
   // Reproject the already loaded descriptors when terrain alone refreshes in the same area.
   if(!vectors&&window.earth?.sourceOSM&&Math.hypot(...toLocal(frameAt(lat,lon),window.earth.sourceAnchor.lat,window.earth.sourceAnchor.lon).filter((_,i)=>i!==1))<1000)osm=window.earth.sourceOSM;
   return {terrain,osm,requestID,source:g.status==='fulfilled'?g.value:null};
  },async value=>{const ok=await renderer.setScene(value.terrain,value.osm,{isCurrent:()=>value.requestID===task.generation});if(!ok)return;
   if(value.osm){window.earth.sourceOSM=value.osm;window.earth.sourceAnchor={lat,lon};}else{window.earth.sourceOSM=null;window.earth.sourceAnchor=null;}
   const ground=value.terrain.heightAt(0,0);if(camera.height<ground+3)camera.height=ground+3;selectedRecord=null;$('object-info').replaceChildren();changed();status(value.osm?'Source geography loaded · unknown detail farmed on GPU':value.terrain.valid?'Terrain loaded · buildings not requested':'Elevation unavailable · ellipsoid datum preview');
  });if(committed)updateStats();
 }catch(e){if(e.name!=='AbortError')status(e.message,true);}finally{if(epoch===loadEpoch)dataBusy=false;needsRender=true;}
}
function updateStats(){if(!ready)return;const s=renderer.stats();$('mode').textContent=renderer.useSurface?'Local ENU / compute':'WGS84 ellipsoid / compute';$('altitude').textContent=camera.height>1000?(camera.height/1000).toFixed(2)+' km':camera.height.toFixed(1)+' m';$('terrain-state').textContent=s.terrain?(s.terrain.valid?'Live DEM · z'+s.terrain.zoom:'Ellipsoid datum only'):'Not loaded';$('objects').textContent=s.objects.toLocaleString();$('download').textContent=(network.bytes/1048576).toFixed(2)+' MB';$('cache').textContent=String(network.hits);$('memory').textContent=(s.gpuBytes/1048576).toFixed(1)+' MiB';$('farm-stat').textContent=s.objects?'192 candidates / object':'Waiting for footprints';$('location-coordinates').textContent=Math.abs(camera.lat).toFixed(5)+'° '+(camera.lat<0?'S':'N')+' / '+Math.abs(camera.lon).toFixed(5)+'° '+(camera.lon<0?'W':'E');}
const keys=new Set();let drag=null;
canvas.addEventListener('pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,moved:0};});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;drag.moved+=Math.abs(dx)+Math.abs(dy);
 if(camera.height>25000){const speed=clamp(camera.height/A,.001,1)*.22;camera.lon=wrapLon(camera.lon-dx*speed);camera.lat=clamp(camera.lat+dy*speed,-89.9,89.9);camera.pitch=-90;}else{camera.yaw+=dx*.18;camera.pitch=clamp(camera.pitch-dy*.18,-90,80);}changed();});
canvas.addEventListener('pointerup',async e=>{const was=drag;drag=null;if(!was||was.moved>5||!ready)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*renderer.width,y=(e.clientY-rect.top)/rect.height*renderer.height;
 try{const record=await renderer.pick(x,y);if(record){selectedRecord=record;$('inspect').textContent=record.name;const lines=[['Source ID',record.id],['Footprint','OpenStreetMap coordinates'],['Height',record.heightSource+' · '+record.generatedHeight.toFixed(2)+' m'],['Generated',record.generated.join(', ')],['Farm objective',record.farmLoss.toFixed(5)+' (not confidence)'],['Data timestamp',record.sourceTimestamp||'Not supplied']];$('object-info').replaceChildren(...lines.map(([a,b])=>{const row=document.createElement('p'),strong=document.createElement('strong');strong.textContent=a+': ';row.append(strong,document.createTextNode(b));return row;}));}else if(camera.height>25000){const f=frameAt(camera.lat,camera.lon),u=(x/renderer.width*2-1)*renderer.width/renderer.height*Math.tan(25*DEG),v=(1-y/renderer.height*2)*Math.tan(25*DEG),rd=norm(directionToECEF(f,[u*Math.cos(camera.yaw*DEG)+v*Math.sin(camera.yaw*DEG),-1,v*Math.cos(camera.yaw*DEG)-u*Math.sin(camera.yaw*DEG)])),ro=toECEF(camera.lat,camera.lon,camera.height),t=intersectEarth(ro,rd);if(t){const g=fromECEF(add(ro,scale(rd,t)));$('lat').value=g.lat.toFixed(6);$('lon').value=g.lon.toFixed(6);status('Location selected. Press Explore to download nearby data.');}}}catch(e){status(e.message,true);}});
canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();camera.height=clamp(camera.height*Math.exp(e.deltaY*.0015),3,5e7);if(camera.height>25000)camera.pitch=-90;changed();},{passive:false});
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();changed();}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());
function movement(dt){if(!keys.size)return;const speed=clamp(camera.height*.65,8,1e7)*(keys.has('ShiftLeft')?3:1)*dt,yaw=camera.yaw*DEG,forward=Number(keys.has('KeyW'))-Number(keys.has('KeyS')),right=Number(keys.has('KeyD'))-Number(keys.has('KeyA')),g=moveGeodetic(camera.lat,camera.lon,(Math.sin(yaw)*forward+Math.cos(yaw)*right)*speed,(Math.cos(yaw)*forward-Math.sin(yaw)*right)*speed);camera.lat=g.lat;camera.lon=g.lon;camera.height=clamp(camera.height+(Number(keys.has('KeyE'))-Number(keys.has('KeyQ')))*speed,3,5e7);changed();}
async function loop(now){requestAnimationFrame(loop);if(!ready||fatalError||document.hidden||drawing)return;const dt=Math.min(.05,last?(now-last)/1000:0);last=now;movement(dt);
 drawing=true;try{if(needsRender){needsRender=false;await renderer.frame({...camera});frames++;}else await renderer.present();}catch(e){fatal(e);}finally{drawing=false;}
 if(now-fpsAt>1000){$('fps').textContent=frames?frames+' updates/s':'Stationary';frames=0;fpsAt=now;updateStats();}
 if(now-lastAutomatic>2000&&(now-lastInput>900||geography.allowAutomatic)&&camera.height<20000&&!dataBusy&&$('terrain-auto').checked){const s=renderer.scene,p=s?toLocal(s.terrain.frame,camera.lat,camera.lon):null;const far=!p||Math.hypot(p[0],p[2])>s.terrain.radius*.35;const scaleChanged=s&&Math.abs(Math.log2(clamp(camera.height*2,1800,12000)/s.terrain.radius))>1.5;if(far||scaleChanged){lastAutomatic=now;loadArea($('auto-vectors').checked,true);}}
}
$('coordinates').onsubmit=e=>{e.preventDefault();try{destination(Number($('lat').value),Number($('lon').value));}catch(error){status(error.message,true);}};
$('destination').onchange=e=>{if(e.target.value){const [lat,lon]=e.target.value.split(',').map(Number);destination(lat,lon);}};
$('load-data').onclick=()=>loadArea(true,false);
$('orbit').onclick=()=>{camera.height=14000000;camera.pitch=-90;changed();saveURL();};$('aerial').onclick=()=>{camera.height=1000;camera.pitch=-75;changed();loadArea(false);};$('ground').onclick=()=>{const s=renderer.scene,p=s?toLocal(s.terrain.frame,camera.lat,camera.lon):null;camera.height=p?s.terrain.heightAt(p[0],p[2])+5:8;camera.pitch=-5;changed();loadArea(false);};
$('apply-provider').onclick=()=>{try{geography=new GeographyProvider(network,{endpoint:$('provider').value,allowAutomatic:$('auto-vectors').checked});$('auto-vectors').checked=geography.allowAutomatic;status(geography.public?'Public preview mode: manual, bounded requests.':'Custom provider applied. Only enable streaming where you have permission.');}catch(e){status(e.message,true);}};
$('auto-vectors').onchange=()=>{$('apply-provider').click();};$('grid').onchange=e=>{camera.grid=e.target.checked;changed();};$('provenance').onchange=e=>{camera.provenance=e.target.checked;changed();};
$('clear-cache').onclick=async()=>{try{await cache.clear();status('Geographic cache cleared.');}catch(e){status(e.message,true);}};
$('resolution').onchange=async e=>{width=Number(e.target.value);try{await renderer.resize(...dimensions());changed();}catch(error){status(error.message,true);}};let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(async()=>{if(ready){await renderer.resize(...dimensions());changed();}},150);});
$('panel-toggle').onclick=()=>$('explorer').classList.toggle('closed');$('fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(e=>status(e.message,true));};$('retry').onclick=()=>location.reload();
$('export-stats').onclick=()=>{if(!ready)return;const report={...renderer.stats(),camera,network:{requests:network.requests,bytes:network.bytes,cacheHits:network.hits},selectedRecord,notice:'Source sizes and generation counts are measurements. No equivalent-GB or confidence claims.'},url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='stratum-earth-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function start(){try{const [w,h]=dimensions();await renderer.init({width:w,height:h});window.earth={renderer,camera,network,loadArea,destination,sourceOSM:null,sourceAnchor:null};ready=true;$('boot').hidden=true;$('build').textContent='COMPUTE ONLY · '+renderer.stats().build.slice(0,10);changed();requestAnimationFrame(loop);
 if(matchMedia('(max-width:700px)').matches)$('explorer').classList.add('closed');status('Earth ready. Downloading coarse geographic context…');
 try{const response=await network.json(SOURCES.land,{maxBytes:4*1024*1024,ttl:30*86400000});await renderer.setLand(response.json);changed();status('Coarse coastline loaded · select a location to descend.');}catch(e){status('Coastline unavailable. Ellipsoid shown without invented continents. '+e.message,true);}
 if(camera.height<25000)loadArea(false);
 }catch(e){fatal(e);}}
start();
