import test from 'node:test';import assert from 'node:assert/strict';import {frameAt} from '../../src/earth/geodesy.js';import {normalizeOSM,joinRings,stableSeed,metres,landEdges} from '../../src/earth/data.js';import {createTerrain,sampleTerrain} from '../../src/earth/terrain.js';
const f=frameAt(0,0),points=[{lat:0,lon:0},{lat:0,lon:.001},{lat:.001,lon:.001},{lat:.001,lon:0},{lat:0,lon:0}],way=(id,tags={building:'yes'},geometry=points)=>({id,type:'way',tags,geometry});
test('known footprint edges and height remain source constraints',()=>{const r=normalizeOSM({elements:[way(42,{building:'yes',height:'37.25'})]},f);assert.equal(r.objects[6],37.25);assert.equal(r.objects[5],4);assert.equal(r.edges.length,16);assert.equal(r.records[0].id,'way/42');assert.equal(r.records[0].heightSource,'source height');assert.ok(!r.records[0].generated.includes('height'));});
test('source levels are explicitly distinguished from a measured height',()=>{const r=normalizeOSM({elements:[way(42,{building:'yes','building:levels':'4'})]},f);assert.match(r.records[0].heightSource,/assumed/);assert.equal(r.objects[15],4);});
test('unknown height remains a zero sentinel for GPU farming',()=>{const r=normalizeOSM({elements:[way(42)]},f);assert.equal(r.objects[6],0);assert.ok(r.records[0].generated.includes('height'));});
test('stable IDs do not seed on tile or traversal order',()=>{const a=normalizeOSM({elements:[way(42),way(43)]},f),b=normalizeOSM({elements:[way(43),way(42)]},f);assert.equal(a.objects[8],b.objects[24]);assert.equal(stableSeed('way/42'),stableSeed('way/42'));});
test('concave / holed source relations retain all edges; member duplicates suppressed',()=>{const inner=points.map(p=>({lat:p.lat*.2+.0004,lon:p.lon*.2+.0004}));const rel={type:'relation',id:1,tags:{type:'multipolygon',building:'yes'},members:[{type:'way',ref:42,role:'outer',geometry:points},{type:'way',ref:43,role:'inner',geometry:inner}]};const r=normalizeOSM({elements:[rel,way(42),way(43,{},inner)]},f);assert.equal(r.count,1);assert.equal(r.objects[5],8);});
test('fragmented relation rings join without inventing closing edges',()=>{const r=joinRings([points.slice(0,3),points.slice(2)]);assert.equal(r[0].length,5);assert.throws(()=>joinRings([points.slice(0,3)]),/Incomplete/);});
test('incomplete way is reported, not closed or invented',()=>{const r=normalizeOSM({elements:[way(42,undefined,points.slice(0,4))]},f);assert.equal(r.count,0);assert.equal(r.warnings.incomplete,1);});
test('provider incomplete results are rejected, not treated as an empty city',()=>assert.throws(()=>normalizeOSM({elements:[],remark:'timeout'},f),/incomplete/));
test('source dimensional units and invalid values',()=>{assert.equal(metres('10 ft'),3.048);assert.equal(metres('12.5 m'),12.5);assert.equal(metres('unknown'),null);});
test('land polygon data becomes edges plus latitude bins, not a mesh or CPU mask',()=>{const a=landEdges({features:[{geometry:{type:'Polygon',coordinates:[[[-20,-20],[20,-20],[20,20],[-20,20],[-20,-20]]]}}]});assert.equal(a.edges.length,8);assert.ok(a.index.length>1024);});
test('terrain keeps supplied elevations and rejects holes',()=>{const t=createTerrain(0,0,1000,()=>100);assert.ok(Math.abs(t.heightAt(0,0)-100)<1e-4);assert.ok(t.heightAt(1000,0)<100);assert.throws(()=>createTerrain(0,0,1000,()=>null),/incomplete/);assert.equal(sampleTerrain(t.buffer,0,0),100);});

test('farm inputs do not vary with the ENU origin or unrelated query members',()=>{const a=normalizeOSM({elements:[way(42)]},f),b=normalizeOSM({elements:[way(42),way(43,{building:'yes',height:'250'})]},frameAt(.002,.002));for(const index of [6,8,11,12,15])assert.equal(a.objects[index],b.objects[index]);});
